name: Deploy zad-ksa.com to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Write SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Test SSH connection
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no deployer@${{ secrets.EC2_HOST }} "echo ✅ Connected as $(whoami) on $(hostname)"

      - name: Deploy zad-ksa.com
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no deployer@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/zad-ksa.com
            git fetch origin master
            git reset --hard origin/master
            echo "zad-ksa.com deployment complete!"
          EOF
